---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml # for all things cloudflare-related
  - traefik
  - external-dns
  - cloudflare-ddns
  #- ddclient
  - wildcard-certificate
