# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
# #? sops --encrypt --in-place "cluster/apps/monitoring/thanos/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:4uT2YBqv7I3s5NPczwzXSMzFWAh+WpOVKj4wFWJRDHRBt2IqkTiROXTYVmq1ZzpnS5tZvQllbuRBYdAPQOqb4e7nHS/6QJqnAkjVsE2gLkg4YYGqrCnbKRLP0oRYWcxapk/WtmL01KZfT057xBKDyL65RLnyGGANpkOshdWowEYWwuvpCpA+JbLIOpxw+5orKRaZ,iv:SLVrxJ4j2cttL0h6i7GsbqFdff7TUkwHXAtGGjHu9fE=,tag:yLFaX8o7FwLB9bqMWncuyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MGdNN3I0Tk1EQU4yQS9V
            NUhpbXRyVUFzQWc2SEZJWVRGOVJycElOK2hVCkJIKzNOUFErait3Ujl0bXpjdnhS
            NHIyc29jWjJrTU95SW15ZzY2MWFkbGMKLS0tIHVUbUo1K3gyRjdzcjRnZG5TY0l5
            MDJLc2UrTjhENU91WGVRemV1MWR2dmMKqtou+9dgs3quOS29KhFSTMpCGdlYc4fa
            z3iKMg+ykXfXvdahLGwKEM4A9c2fKLt7xDVgyIFDxF0OghEf0DMu6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-14T18:23:06Z"
    mac: ENC[AES256_GCM,data:L9pzjIL4JWwJKdn3bXzHS0gVstY99HVw6knDJclNCU29/iWTDQ/cawR1ADnrl6+6VfPPIJT6jPN7SlcGyYUIViBeCxO2NZPbTsXPFw4M9xgbF6kseMBMIuFkgT1k8+otjVVNRD9B6X7wEUr3+A8QiNuUIted7AN0wEIVL844Vts=,iv:NvKc6pZU4LIJ/icgEzYlsVEu+58OQmZqy0ZS5Zw6KnE=,tag:+JWGYlHnlRsvU2AUwW/7Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
