# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
# #? sops --encrypt --in-place "cluster/apps/monitoring/thanos/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:PUn0ym+D9NFp4/q+5vDfbeJNve+wTh7XSJY5CQDSr3fRN4YbYz6F9ThtzHwLaJbjVVFw/rkOCq152fJ1smXfBYmWFuLm3Z6kDHJ1T3CdqoinaJ9ZwGk+c7eGLQPcmQyoppoyDjzCN93fvqwECMB0Z1SEv2vyfLCDaCfwC8/94gaklTexITMqy521g3jVdjqfWuuiA+U=,iv:9bCwHlkV1fdDhTUox14MbJqJ+wjEjTo8zsvUikstHtU=,tag:a+Pq//NsZQl+lK19iVaYuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MGdNN3I0Tk1EQU4yQS9V
            NUhpbXRyVUFzQWc2SEZJWVRGOVJycElOK2hVCkJIKzNOUFErait3Ujl0bXpjdnhS
            NHIyc29jWjJrTU95SW15ZzY2MWFkbGMKLS0tIHVUbUo1K3gyRjdzcjRnZG5TY0l5
            MDJLc2UrTjhENU91WGVRemV1MWR2dmMKqtou+9dgs3quOS29KhFSTMpCGdlYc4fa
            z3iKMg+ykXfXvdahLGwKEM4A9c2fKLt7xDVgyIFDxF0OghEf0DMu6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-14T18:34:09Z"
    mac: ENC[AES256_GCM,data:iN6+8xHjX3DXLdqFhWuZnZdIsTZ5EMzcXropI1DI/vYn3suBsf3xXnESzBoGgcguaUEfQ+I0UcbKJyhslGYzYUK7p+YvYvygp9B521SKNAWtn7iBNYg6/Jn0sBaS2dUwZdCIBxCP72+lQp+xPc7ftbURa9IrH3RgabM9apJOTRc=,iv:b4r62vyVWk3H7UN8+PCvbxOUfiDWYfcmEF7BNjW5eaA=,tag:+UbU9vAtBAzPP+EgK7BW1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
