# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/storage/minio/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: tools
type: Opaque
stringData:
    MINIO_ROOT_USER: 
    MINIO_ROOT_PASSWORD: