# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/storage/minio/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:CLfkiaeRX0GvPfQ=,iv:ttn7m7EHBcZvngzJxxuzou5zXJ7s+46L/MtgGuIvsuA=,tag:xPzBgSCzGje6GfTKHcsCMg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:/tfi4GU4+zt3FcsfViY0j4nUZgjek3OAn2ssfA==,iv:VAHg8tkjIU1NhafW64ohHUKNULZjilQDmff4eBAU/I0=,tag:b7K7a7XLf+2J1eiJ3pGlxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSzVCT1plQVM0Nm92WTEx
            RzM5d2wzZUJaNnRkY2dNT3FKNW9QRnJQeEg4CmxRaUc0ZG9ENWtacWtiemtPcVox
            eTBJa280ZWNOMTBoUzhhbUttTVJRbkkKLS0tIHVSbFRLWEh6RXNKZkJlbGhYVFFr
            Y1RTcmNadzh2Y3U5cTZCcHRKZ2RZU0EK4YV4+OQWcgRLqjZpO7XUCyMnt8eYuONA
            hveG8RzF51GgdJaWyjYmPhCUcgCoG+XHmqDFRqjy3VRUMOCMzMdmWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T17:37:30Z"
    mac: ENC[AES256_GCM,data:eOyseGktCUoyylObxqiHjeu62vJf5TRxpoUBqPQZAfrDxmgty1yCoN/nCeDhu4OBKuyou/X/OOPJmFY/7YEPC1wVFSlWCi5UNWj8QU8gPRsSDOxH3XEDdwTJ5MCiUGnTQrJ9XkVv5FO0wNyQQxFoVT3BSpxjYhfjSn85zJffLyw=,iv:lhDrX8nZLvwOkgXrgdyYcKerXyhPbYvw+HIU0cFU4bg=,tag:GARi2+5g9WaE+EKRm6L8+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
