# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/networking/cloudflare-ddns/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SjvRn6RGs5U2MZ46ZCad/XwJWXrp,iv:ZqMHYKOnxvivldbZQhbN+zOUfG/vxN+sGeSiotM9p+0=,tag:Q1ClEmy+tWZg6PoZdd6xSQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:N0itGviZB1oEAN0XJqqEJOVi6jHuFps2JQgbXBGM9tgibjmNjQ==,iv:5BR590tGhHZ/v9Rg7k9TEqVaS0Bkv3aV5wgyMAa/Uh4=,tag:IcgilRIlqlphiTHRqZLa2A==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:Jbbx4x3Rg2EbMF55COLojPEDhjyqF6BjKGgq49GX44M=,iv:N3cw6mKt7r+tWXzgbE/e6skH1uc3vVsGDWGZweAVYD8=,tag:aaSBcyMLj3TvOf+c8aZAOg==,type:str]
    #ENC[AES256_GCM,data:/qXF6hn9OWjcumxUu9C+ToUZoMoIVQ==,iv:QtATMUqnHWXnuvWqp+iTA8NR3XuycuXGYTk3v6HK8zc=,tag:PQDwbsV33Os8FYtJZSAiig==,type:comment]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:W+k0BCjk6Oz17BEDKoi8grXAoM6C,iv:jZXEECHZ5rWSWbjrIVzdKyRgiMVbbf7ZSovGwxlNF/E=,tag:5LmCOUhoksQ4w5eZyk2XrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVAwaGRvazdVN3FDcVV1
            WUptVGllcVlSenIvazJXRldLVWYrSEFXYkN3CkZGZ29DYnB3V21mbW9McGhPS1Zy
            dGk3S0RITk9wOVNDa1VMVkk1V0JvNjAKLS0tIDZTTUdxQ3ZyazBpN2dUYTh1Ym1y
            M2g0blI5NTJhYXhmOXorU3pUQ0RwVzgKdiTF/VKBIquxz26M05vo5hPsqy6ulpaR
            uId2OAs5fI/V7LgbXjX0xILUmod/r7DCCJAUUyrYJhi+J6WKiGMmmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-09T16:50:55Z"
    mac: ENC[AES256_GCM,data:28+Qf2Y584dYl1q1X9z11Je2VSLETw0Z50Ud/oHHooIXNYxTG6hvZzdrChwe9pexLEwTZOZzxJ3gPm7/8xesL5bAR90EBgwg3bO7T2ZWd2qe6sMhj7PbYdBHt8Xs99XBN849D5WDhOq1/zPKET1MMTj+Wvg8WC826WQrhfnzlZ0=,iv:Qv5JXA9piZ7YgF91oWfUM8YwiNcKhSDaG8Yi2qMTL10=,tag:10Dzz9j9AisVc9kylUd02A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
