# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/networking/cloudflare-ddns/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ncv/WxGdxWW/h0RjoiIbdlj0E4Oh,iv:jplIWB81MG2HSXx4VlmHm7A9gZwj8GDXCnxtI4JRpQ4=,tag:vnjNct068g9UjPNRAgw12g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:DFev1LN0thnEqOZIv7Dl3/hHy94YoFKa2q3ynzrRF5wNEIdRMw==,iv:qBrGx8aTgoP4eKe58djJljWb+zHcFUZKWCQnFRmmIiI=,tag:YiilvIk63JDTFGcVprNoPg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:2gZBrRbDBOxQ76IMEkfns1RdTimjNInhEhdW0PXsQjo=,iv:V1vxHo/OPHPu8Iwzj9uh44MK/lcud8c/DNJIPDX0Rd8=,tag:7sn34avnqgJ+FuQMOFmS8A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:yAwnlw==,iv:yj13eXnFtFC3DpvF9pxJloGWu5Kgz3xECoDrAOUrOiQ=,tag:FzLzy5xf44sFi29pShKZxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVkFrSFBma0dUU0NMc0lt
            V01sTzJLZnpTU293K050cjhjaW1tSnRTWDFBClZybmdXbHhNMnFjcS92TlE3SGJR
            QnowQWo0aTJoV21sSHR0aUJXNGpqdk0KLS0tIFZueHpLYXk2bUpuTytHVVhPZitH
            ZC85Z2lVTW5GbXk3OWo5MlhyZDdGL0UK10YTTwRWh1vWmjRhvKZJYhhBMBCab4ZY
            UhenkUiaLfujuuB4GazbIGSY488JxAML4xTgkXjQn0IfIB2eE6H1ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T21:50:32Z"
    mac: ENC[AES256_GCM,data:y1/xZ8ED6PfCghoDGF5/YG6xTqTyvymtqjgWEQ/mDREmu96MM4TihdZkWk5sQLigR9c5T20i4i3Fq8nWkvKzrUHC0AaQCivi71EZm7XSnEh7cp9lYB0LUhKGhQh5dSbn6O1R0Pkl2haQ1VLybg4CuZOr+9NPmyGOBBjJhoy6TyE=,iv:TOXGkQ8RxrxPN3p+/NnRx0/IK3FMzqoP+mEADtjqlWY=,tag:UtSX3ZBP/eminltv2x3u8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
