---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-config-v1
  namespace: tools
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #? replace me with your storage class name
  storageClassName: hdd-nfs-storage
