# yamllint disable
# #? sops --encrypt --in-place "cluster/apps/networking/external-dns/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:1bCKVm+QoOr1CHClLQl8ICcgkVTw,iv:xmVNKVbHcXBFDLscgz5apVdy9u5GEmnjee7FQiixeTk=,tag:ZB8GFxm/Jkud7xI7EXZrKg==,type:str]
    api-key: ENC[AES256_GCM,data:CksM3zJ3EjFacqLL8P9CsrzrdiinhS22O5MupLPCvTNkjbDcdw==,iv:7qAVlQQGxnqcmW8gq8mMTmxwlwMezLi7gHpjy047uPQ=,tag:VQ0aeQlWQnoOg5JwRU3r7A==,type:str]
    #ENC[AES256_GCM,data:oOrjT3WxnES4c4jjN2O2WsrTtb3Q2W/WGs/NcFGjSsi81/cfERVnrbA=,iv:qwcCrPdhekq9rUGmP1sO9MeCU+ioTS4GWCLzFuWvYJA=,tag:MWRfi6Zlh4ClkrnK+bUzfQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTllLbENoRE5WNDdQK3ow
            dHRNZTExempHYVgxaFQ3VTFwYitTQWo0aEJvCm9XY1huYmVVWW1lUTBqYmhXSkZn
            SDBzQjFnaUVRUy82SGR0elVHNWtzbUEKLS0tIFF5MENrWHIweGxhNyt2ODJ0eVhT
            KytFVXhzSHV2ZFE0YUNsM1N0bEhMdGcKKCXCFlFNJK9JRL254fYm9jvN6uJM4c/Y
            g3Psap+GxZ3C0tI4SO03JQOSTbxZEopc9/531qj9iFbXUa3ZC2c5mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T00:12:55Z"
    mac: ENC[AES256_GCM,data:o+oDayT53VQpLvphLJkyB/1/bPWALdzO3Z48v70OIX656Nj5hsYajXqFpnWU1aZzXvNJPMepov1xhdRXZkNgW5kwXj+AFQRU37KI+rHa8OOqb0p7omgGuObmpjZ6Y8xSwWyriA1H+iOhPiubc/m80FW6lJaVXqP15d9jfvkxfr4=,iv:2PiaXd4mGiC1tlZmLNmEPF9gF2pU3jnrq9iMHG5wkYQ=,tag:QFSRMZ3H5mDUMQOVVJ/0Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
