# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/eM7MIbCqB+7essovFBqkw==,iv:xGLKpW/a527PDxExn1vzrfG3FRXojgBPKQfj7Zf146E=,tag:7VQO2+IcrKtRW1drXNMhng==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MGEK8t3NwadkwrZc5HW3R5QIJ/qQ,iv:3xN3HjrWjRhuJ8jhJydbgfFxk1aNQavDhlrTz8biK6I=,tag:inGqsv5WmLxJKaZ78KI3Xg==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:IWQH/XEwrTWEFDdI/Ib19epenBRXxRit7GI0VuOo7H9thJ9HIA==,iv:gi5uBMiq8zJIp5hpDBYu57/09kvFBY47U+Q4xjqXuJ8=,tag:y5h2oN59tJXj+C7tHMEDjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbGdFM3RGUUs2ZXNyakRV
            bnJlNkpkUXdFOHg2WDYvbE45VWpoQmd6UFUwCkVNeFVzU0JJSVQwdjY0ODZKaTRH
            d1FVNnhQL3hDNE02UUVpNUVSc0RIcjQKLS0tIFZkYTRXMEdMOUhyMVJUWmhBRnhH
            UW85aktiRFl1VFVtM0p3ellpZDZWZzAKS1C9vrhXeqBWbQE1yf+fxWhUUKEE+aAe
            ntHCKS0vzi7tqsVzlfgAhyLL2sJCCLsag3RXPjJfcniZxtR0xLf0uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T22:09:00Z"
    mac: ENC[AES256_GCM,data:TR4bisDk+c7psFEP3nov84iaHJmM3i8bSBXo6dLyz17XWHL+ImxRyfudIxs7uIWl8OFg/cwKuzlUvnEPqx+SS0/oIGW/YGKWUSWFh/l760EYt4q9t8K6FbRn8Z24vtTCpCLcq4YM2qTJ3uh3SQekcBs2aqO1M+hbPHbztSGo3Wg=,iv:kCZGn6fwBbTeCLj7ojT2KdjHoeycQLYt6YiIEEARXsU=,tag:Q29e7TgfmFVmLdJN8YJTDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
