ignore: |
  *.sops.*
  gotk-components.yaml
extends: default
##! this was the original ##!
# rules:
#   truthy:
#     allowed-values: ["true", "false", "on"]
#   comments:
#     min-spaces-from-content: 1
#   line-length: disable
#   braces:
#     min-spaces-inside: 0
#     max-spaces-inside: 1
#   brackets:
#     min-spaces-inside: 0
#     max-spaces-inside: 0
#   indentation: enable
##! this is more relaced ##!
rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
