# yamllint disable
# #? sops --encrypt --in-place "cluster/base/flux-system/notifications/secret.sops.yaml"
apiVersion: v1
kind: Secret
metadata:
    name: discord-secret
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:gxI+O0ThPnhp7PAvsiR/RlcHT2nRZrri9KuhITZ+VTJ4aLXy4sV5djgK2PgHz9cqqwlCNGMpgiSQ6sBwhEC4DQVaIgbxLhjEsygrcFFRPkxmMgP76eY/2mAvD6qOQdWbEbUf4+6sTcPQoGfutF+2nuDVzHt4Lvql,iv:7yy18Kb8523ghGhf14k3nj+rnTWkxAzq3L/w7XhuTxY=,tag:38nOpfCwyqwCOu7NwYmjgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc0lNVW91MzloelQveFpH
            UnA4VEo2ZklGdkF6V3k3M0E0ek1pSkdlQ0cwClJwMElTcmdQNHY1aDBNTXB0cTJ1
            Y25ELzJIeGRzZkVmVDRyZWxCTXBOajgKLS0tICs1eEJFaDVaUERFTUhLQjNSQTFT
            ek9oNHN6ZFVpekdjcTRmUGMxMTlaemMKDgFxuv1yaDBMDfFvhtlQtQGuRH7ubjmJ
            gO98vSR+FzgFr2ykCyCSrmTYF/olJZh9xBs2wvOw7O/u+8TQBavETg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T00:13:21Z"
    mac: ENC[AES256_GCM,data:OF0FooobLlkY94SD6ZyG8A1xLgs5i6xi4KkGQ+GzKqQus7PgchUQUp6eLgb46KxItUckHuZAvG6rVGrfTzf4zNBTwyIsreUjXBMg8qenUbiZ4wqsyE1mr7kbmKhH4+1s1JOReTouv4PEpqMJmXS6haFnkfRQtrMVh2mKMqiPE44=,iv:0TrcMrq0LF0rNAaX5ub6fRZs+8apkqB612CQnt2e2o8=,tag:C+wHQN80NfUNiDj+aDv7SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
