# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:GUVUQQvwVy8gBjmMGePsEmX/xYg8LJ9pF70pNK/PvHmoBqyuAA==,iv:UlXzf035XVJzqbQsdpIy2cuK4ciyQtBatgOhNa6C5jA=,tag:/PUn6Ai5McYZMvlDkSfgfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVXlsTEJpaVh3bUJwTWVw
            SWU4V082RWRSN3pvTnlPczFRaE1ObmJFVGpVCjNnRDg1Y0NVOGlvUWJ4VVJwN0dP
            RzhLTjFkMW1rQTJQc0t2c2dXWitKVVEKLS0tIHRpNlNTK25kT3NOT1RSSU0wSVdt
            aENtQnRTVU5ZZ3ArU2tzbWRmd0tId1EKpT0TDlpwV36mm9q0QrFIk5I4cd+th0lO
            MrXn8kzJX5Woyu7Pn9MCfYKaO7NO/YBaana9WO3KwpWcJicbXQF+dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-03T18:17:59Z"
    mac: ENC[AES256_GCM,data:lnyBrtHhWTvWzP8eLEXEpmNGaN8v+7yH8UYKT8aqOv4ZjkV2JOSiTvE4f+rfhrCJ0H1mruc1iEmrxZbX8CmO7ZLmvlJEIuT02AQD9hjpNkBN6WZ4BJdCCY9iH8MUyKk/D9LsRw6VPXmjROw/aSnUr9VV/Iud68VY5YqJM6lWAv0=,iv:lwmTR+rxd78uIveRDwTukcqrqLqPjXCXWGe7TQZq5IA=,tag:bOM+E7E8GPZOWiiCuCsHSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
