# yamllint disable
# cloud: |-
#     [default]
#     aws_access_key_id=
#     aws_secret_access_key=
# #! sops --encrypt --in-place "cluster/apps/velero/secret.sops.yaml"
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:QyWi1VwRJDMZeiAEBVcdxO+rhL4eb3EnT/wiO9GwMt0EBv3COyC1krq3f7i+ZDcHQO8ERRMGKxW5Prmad6D+z8Up1x4dYsRc6nIgbMkC2EDABc1R,iv:VLpmAU6tlgtX7RhvSh58hhNR7iga122cp6n03aINE0o=,tag:MgExfeq+CUISwYDGLA54Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSDdZbnpsNk1xQnNuU1lw
            bEpSWFhvMHNhSUlmZFZlcnh4U05FMHFoc1NJCkVodFBKWGZ5N2FmOFBNSERNbVo4
            WnFnREQ2R2IxTkI4VUMvY2orNmRvNEUKLS0tIEYrajU0VlQ4YS92bERRbWNGLzh0
            Tys1VWlOUmt0c3pQVnZOMFNtSXJnb00Ka3coZ3S5vQqDnrqDfyT5/a09Ktolcq20
            Iq3zaXnV4QY9ZV77zFTuPrN3dGwdHHfcSIyd2ocjaM4TRBtgtHzVMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T18:53:51Z"
    mac: ENC[AES256_GCM,data:6f3uY7gz7lg66i8l14YQIK7rVt2sudhmIr/5qovraZkgHFsZRLsRI3rYq4udwU2zfPs0E5TTwG71WIDvp/9vEvhrF7FVWQ2YtgHAzCfSK7V4doKqVJGaa+QYLwv7yWBrbTrC7z7GLaMmShmW9URe7EYsBwO1PEIQ8tto3lRW0As=,iv:bF2pxPTt1HAoX/W6RNIfQV+zDOmRM/u4bcbQxOSw2Tk=,tag:DNUoeYMYRxnMHAZM6Oh+Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
