# yamllint disable
# cloud: |-
#     [default]
#     aws_access_key_id=
#     aws_secret_access_key=
# #! sops --encrypt --in-place "cluster/apps/velero/secret.sops.yaml"
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: minio-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:YNpe01japMJC6x4g+66mED7Mm5FvPeqVclizDkKrzOPJiigdYhVhyAiqO4UZpyYgUknqF18/r8PNa4TF87OMNzwW4mcAULtykeAnug6DaH7XYNpq,iv:2CmYh3QLpvRbZOMhuPqlwa12tfoSsfZXto+bHFhhSWQ=,tag:DihljajSb72JbLq1h/inMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueTdtd3BaZDJzNVQ5eURn
            d0Z2QWVUZ2ppSTg0cHVncDQxT2NORkxNMVgwCmF3VjVMNE43TVN6Rk9nb09IUWl1
            UUNWNk5HVWs2VEI4ZE4vY0tNdXltTE0KLS0tIGw3a0p4dmlmRTRFU2hVT1BIMzN0
            MjJYeGI2R1RLazJjKzFrN1J6ck5BMnMKFUA8XF9WZHV2nq+YozjO8tOUytHg9mey
            CncYnUJu+HG2vSsjJ92xWmt6Vt+Wi1vznJuBZ974MCDXWT3h7Zrh2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-08T13:12:48Z"
    mac: ENC[AES256_GCM,data:N1+sKbRls2WvxW3QCBsQiDDIWjKD3tiMlG/uIBpatM0QOIKREIIs/16zH64JmV6bUl0Ah4pn628sW0i9n3LfT82VUwy43WvRue6TcKqj47n4Ik8iuJCeyVRAyR1ZAyD7O6LLtvXFKC81Mp/yBGWOopt4bfhB2I84hBdSvyr9dM0=,iv:FYk3lYn/4hWsZ1F57UO1vtUw8VN271cnaE8JyEkJ+d4=,tag:6Ty9R8oKf2A4KsIDozTv/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
