# yamllint disable
# #? https://www.botkube.io/installation/discord/
# #? sops --encrypt --in-place "cluster/apps/monitoring/botkube/secret.sops.yaml"
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:hN6WtTnbIjI2UWW8Ks9d92uH5vl0OncM52Ikv+dIm3ZFxArL8Ad1Nr9YO1c/ETbGlAwCR9WqB6uZAMgn8O9I1Q7AgaXMCDxmPZIrxPFvuXgMSOAJOGmv+tzsnkhGoNMLYEFD1fWEpNZFHIwKyN8pxPAAUn3M2YirWnEONONPK4g+ohcAfrpeJx86ymngfiGRh0ReVuO/rsOeIwYRXYjqTp65+mblei0cH9QH8yA31M9+YWIg/SIM4gAUyWvjamdErWCyzb4Jie81wxov5T1Ez0YmNr4BLxePO0WywqM=,iv:DYNToXz/ibmHqEZfqWE9In0RRCl1MQ+GpqSDrbC1vKc=,tag:UeNgbR66TRZirgWkh0ygCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf96qp7qw038fej7rryvp04qgfakxcv5gg8ew4v5jc2d0xwryvusare09d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODBIZ1pUTVlXKzBkTG0x
            V1dRSnMyQkRHeUVIMHYzUmhJMHdHWWI3TmlNCmx5NzFIa0VSRXBsTWpqYXlqUWRU
            RGlNeHBoU0owZDJZYURGa3VYU3NyOVEKLS0tIGtwUHNYMUgvbis2dGJic3NtdXdU
            NmR4YjJ1QTlnUmJxdXFPZzM3M0Jrc0UKWK2xJZ+VvuR48hbAN0EDXMmOBoRdnFHf
            a0WNFKaadMqr492SCEPUOeBpwDvV+JPyJc0ZbDJo1vy/Is84Ja04Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-08T18:52:50Z"
    mac: ENC[AES256_GCM,data:2zGM9cvheG8R0keI5Q5SmIg1X942ovNUHOmaHJYwQ0rp5eY6q7eqUK6P3m8jCsj7bo8BgP0X8xLQ7eQSJgT1mSJNMgEHgHE3rjazd/RNcCWLy2I/6M/P5bUaWDLcZs1a7y2SC7Sq9lxcHzxCOKggQE1dS8N7kcC1OO6hlOks39E=,iv:cw3HmiXnjJFcZvw7zETWu90xclgRdVxi/eXb2eCH7Vw=,tag:RAtg0G0fydiZ/BEpuwdOMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
